version: 2.1

jobs:
  build:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run: echo "In docker..."
      - run: |
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt-get -y update
          sudo apt-get install -y libboost-all-dev
          sudo apt-get install -y tree
          sudo apt-get install -y gcc-8 g++-8
