version: 2.1

orbs:
  codecov: codecov/codecov@1.0.2

commands:
  preinstall:
    steps:
      - checkout
      - run:
          name: Installing sudo
          command: |
            apt-get -y update
            apt-get -y install sudo
            sudo apt-get -y install software-properties-common
  dependencies:
      steps:
      - run:
          name: Installing dependencies
          command: |
            sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
            sudo apt-get -y update
            sudo apt-get -y install libboost-all-dev
            sudo apt-get -y install gcc-8 g++-8
            sudo apt-get -y install libpng-dev
            sudo apt-get -y install tree
            sudo apt-get -y install wget
            sudo apt-get -y install curl
            sudo apt-get -y install lcov
            sudo apt-get -y install libsfml-dev
      - run:
          name: Install lcov-1.15
          command: |
            wget https://github.com/linux-test-project/lcov/releases/download/v1.15/lcov-1.15.tar.gz
            tar -xvzf lcov-1.15.tar.gz lcov-1.15/
            cd lcov-1.15/
            sudo make install
            cd ../
      - run:
          name: Building essentials
          command: |
            wget https://bootstrap.pypa.io/get-pip.py
            sudo apt update install python3.9
            sudo python3 get-pip.py
            sudo python3 -m pip install pyyaml smake
      - run:
          name: Installing smake
          command: |
            pip install smake

jobs:
  testing:
    docker:
      - image: ubuntu:18.04
    steps:
      - preinstall
      - dependencies
      - run:
          name: Running Tests
          command: |
            mv smake.yaml smake_temp.yaml
            iconv -f utf8 -t ascii smake_temp.yaml > smake.yaml
            tree
            smake testing -j8

workflows:
  ubuntu-18.04-installation-and-port:
    jobs:
      - testing
