version: 2.1

orbs:
  codecov: codecov/codecov@1.0.2

jobs:
  build:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run:
          name: Installing sudo
          command: |
            apt-get -y update
            apt-get -y install sudo
            sudo apt-get -y install software-properties-common
      - run:
          name: Installing dependencies
          command: |
            sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
            sudo apt-get -y update
            sudo apt-get -y install libboost-all-dev
            sudo apt-get -y install gcc-8 g++-8
            sudo apt-get -y install libpng-dev
            sudo apt-get -y install tree
            sudo apt-get -y install wget
      - run:
          name: Installing Cmake
          command: |
            mkdir -p $HOME/usr
            export PATH="$HOME/usr/bin:/usr/local/bin:$PATH"
            sudo apt purge --auto-remove -y cmake
            wget https://cmake.org/files/v3.19/cmake-3.19.2-Linux-x86_64.sh
            sudo mkdir /opt/cmake
            sudo sh cmake-3.19.2-Linux-x86_64.sh --prefix=/opt/cmake --exclude-subdir --skip-license
            sudo ln -s /opt/cmake/bin/cmake /usr/local/bin/cmake
      - run:
          name: Installing Zhetapi
          command: sudo ./run.py install -j 2
      - run:
          name: Testing Zhetapi Installation
          command: ./run.py header_tests
  port-testing:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run:
          name: Installing sudo
          command: |
            apt-get -y update
            apt-get -y install sudo
            sudo apt-get -y install software-properties-common
      - run:
          name: Installing dependencies
          command: |
            sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
            sudo apt-get -y update
            sudo apt-get -y install libboost-all-dev
            sudo apt-get -y install gcc-8 g++-8
            sudo apt-get -y install libpng-dev
            sudo apt-get -y install tree
            sudo apt-get -y install wget
            sudo apt-get -y install curl
            sudo apt-get -y install lcov
      - run:
          name: Installing Cmake
          command: |
            mkdir -p $HOME/usr
            export PATH="$HOME/usr/bin:/usr/local/bin:$PATH"
            sudo apt purge --auto-remove -y cmake
            wget https://cmake.org/files/v3.14/cmake-3.14.2-Linux-x86_64.sh
            sudo mkdir /opt/cmake
            sudo sh cmake-3.14.2-Linux-x86_64.sh --prefix=/opt/cmake --exclude-subdir --skip-license
            sudo ln -s /opt/cmake/bin/cmake /usr/local/bin/cmake
      - run:
          name: Install lcov-1.15
          command: |
            wget https://github.com/linux-test-project/lcov/releases/download/v1.15/lcov-1.15.tar.gz
            tar -xvzf lcov-1.15.tar.gz lcov-1.15/
            cd loc-1.15/
            sudo make install
            cd ../
      - run:
          name: Running Port Tests
          command: |
            ./run.py port -j 2 -m codecov
            export CODECOV_TOKEN='1ac6a585-4a77-4592-a34c-c3e16a19b77f'
            ./lcov-1.15/bin/lcov --gcov-tool gcov-8 --directory . --capture --output-file coverage.info
            ./lcov-1.15/bin/lcov --remove coverage.info '/usr/*' --output-file coverage.info
            ./lcov-1.15/bin/lcov --list coverage.info
            bash <(curl -s https://codecov.io/bash) -f coverage.info

workflows:
  ubuntu-18.04-installation-and-port:
    jobs:
      - build
      - port-testing