version: 2.1

jobs:
  build:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run: echo "In docker..."
      - run: |
          apt-get -y update
          apt-get -y install sudo
          sudo apt-get -y install software-properties-common
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt-get -y update
          sudo apt-get -y install libboost-all-dev
          sudo apt-get -y install tree
          sudo apt-get -y install gcc-8 g++-8