version: 2.1

jobs:
  build:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run:
          name: Installing sudo
          command: |
            apt-get -y update
            apt-get -y install sudo
            sudo apt-get -y install software-properties-common
      - run:
          name: Installing dependencies
          command: |
            sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
            sudo apt-get -y update
            sudo apt-get -y install libboost-all-dev
            sudo apt-get -y install gcc-8 g++-8
            sudo apt-get -y install libpng-dev
            sudo apt-get -y install tree
            sudo apt-get -y install wget
      - run:
          name: Installing Cmake
          command: |
            mkdir -p $HOME/usr
            export PATH="$HOME/usr/bin:/usr/local/bin:$PATH"
            sudo apt purge --auto-remove -y cmake
            wget https://cmake.org/files/v3.14/cmake-3.14.2-Linux-x86_64.sh
            sudo mkdir /opt/cmake
            sudo sh cmake-3.14.2-Linux-x86_64.sh --prefix=/opt/cmake --exclude-subdir --skip-license
            sudo ln -s /opt/cmake/bin/cmake /usr/local/bin/cmake
      - run:
          name: Install Zhetapi
          command: sudo ./run.py install