version: 2.1

orbs:
  codecov: codecov/codecov@1.0.2

commands:
  preinstall:
    steps:
      - checkout
      - run:
          name: Installing sudo
          command: |
            apt-get -y update
            apt-get -y install sudo
            sudo apt-get -y install software-properties-common
  dependencies:
      steps:
      - run:
          name: Installing dependencies
          command: |
            sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
            sudo apt-get -y update
            sudo apt-get -y install clang
            sudo apt-get -y install make
            sudo apt-get -y install libpng-dev
            sudo apt-get -y install wget
            sudo apt-get -y install curl
            sudo apt-get -y install lcov
            sudo apt-get -y install libsfml-dev
            sudo apt-get -y install ninja-build 
      - run:
          name: Install lcov-1.15
          command: |
            wget https://github.com/linux-test-project/lcov/releases/download/v1.15/lcov-1.15.tar.gz
            tar -xvzf lcov-1.15.tar.gz lcov-1.15/
            cd lcov-1.15/
            sudo make install
            cd ../

jobs:
  testing:
    docker:
      - image: ubuntu:18.04
    steps:
      - preinstall
      - dependencies
      - run:
          name: Running Tests
          command: |
            mkdir build
            cd build
            cmake -GNinja ..
            ninja -j 8

workflows:
  ubuntu-18.04-installation-and-port:
    jobs:
      - testing
